# Generated by Django 5.2.5 on 2025-09-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0002_customer_verification_token_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='document',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='document_type',
        ),
        migrations.AddField(
            model_name='kyc',
            name='BVN',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='NIN',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='location_verified',
            field=models.BooleanField(default=False),
        ),
    ]
