# Generated by Django 5.2.5 on 2025-09-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0003_remove_kyc_document_remove_kyc_document_type_kyc_bvn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='address',
        ),
        migrations.AlterField(
            model_name='kyc',
            name='BVN',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='NIN',
            field=models.BooleanField(default=False),
        ),
    ]
