# Generated by Django 5.2.5 on 2025-09-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0004_remove_kyc_address_alter_kyc_bvn_alter_kyc_nin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='BVN',
            new_name='bvn_verified',
        ),
        migrations.RenameField(
            model_name='kyc',
            old_name='NIN',
            new_name='nin_verified',
        ),
    ]
