# Generated by Django 5.2.5 on 2025-09-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0005_rename_bvn_kyc_bvn_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
