# Generated by Django 5.2.5 on 2025-09-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0006_customer_recipient_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='recipient_code',
        ),
    ]
