# Generated by Django 5.2.5 on 2025-11-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userreg', '0007_remove_customer_recipient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, default='2004-11-10', null=True),
        ),
    ]
