# Generated by Django 5.0.3 on 2025-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("account_num", models.IntegerField(default=1234567098, unique=True)),
                ("phone_num", models.CharField(default="0987777776", max_length=20)),
                ("date_of_birth", models.DateField(default="2004-11-10")),
            ],
        ),
    ]
