# Generated by Django 5.0.3 on 2024-09-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='signup',
            name='last_name',
            field=models.CharField(default='Princess', max_length=50),
        ),
    ]
