# Generated by Django 5.0.3 on 2024-09-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='2004-11-12'),
        ),
    ]
