# Generated by Django 5.0.3 on 2024-09-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0002_rename_full_name_signup_first_name_signup_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='other_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='signup',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='signup',
            name='last_name',
            field=models.CharField(default='Princess', max_length=10),
        ),
    ]
