# Generated by Django 5.0.3 on 2024-09-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reg', '0004_alter_signup_email_alter_signup_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
